version: "3.7"

services:
  app:
    image: node:14.17.0-alpine3.13
    # ports:
    #   - 127.0.0.1:3000:3000
    network_mode: host
    volumes:
      - ./website/app:/app
    working_dir: /app
    command: npm run dev -- --host
    tty: true
